import "./globals.css";
import { StoreProvider } from "./reduxFolder/StoreProvider";

export const metadata = {
  title: "Note App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
